'use strict';
apps.snake={title:'Snake — Arcade',icon:'mines',width:465,height:520};
apps.memory={title:'Memory — Arcade',icon:'computer',width:450,height:505};
const retroRender=renderApp;
renderApp=function(id,content,state){if(id==='snake')snakeGame(content,state);else if(id==='memory')memoryGame(content,state);else retroRender(id,content,state)};
for(const [id,label] of [['snake','Snake'],['memory','Memory']]){const b=document.createElement('button');b.className='desktop-icon';b.setAttribute('aria-label','Ouvrir '+label);b.innerHTML=icon(apps[id].icon)+'<span>'+label+'</span>';b.onclick=e=>{if(e.detail===0||matchMedia('(pointer:coarse)').matches)openApp(id)};b.ondblclick=()=>openApp(id);$('#icons').append(b);const menuButton=document.createElement('button');menuButton.dataset.open=id;menuButton.innerHTML=icon(apps[id].icon)+label;$('#start-menu .start-items').insertBefore(menuButton,$('#sleep'))}
function snakeGame(content,state){content.innerHTML='<div class="arcade"><div class="arcade-score"><b>SNAKE</b><span>Niv. <strong class="snake-level">1</strong> · Score : <strong class="snake-score">0</strong></span></div><canvas class="snake-board" width="360" height="360" tabindex="0" aria-label="Jeu Snake. Utilise les flèches ou ZQSD. Espace pour faire pause."></canvas><div class="arcade-actions"><button class="snake-start">Jouer</button><button class="snake-pause" disabled>Pause</button></div><div class="snake-pad"><button data-direction="up" aria-label="Aller en haut">↑</button><div><button data-direction="left" aria-label="Aller à gauche">←</button><button data-direction="down" aria-label="Aller en bas">↓</button><button data-direction="right" aria-label="Aller à droite">→</button></div></div><p class="arcade-help">Flèches / ZQSD · Espace pour la pause<br>Un niveau de plus toutes les 5 pommes.</p></div>';const canvas=content.querySelector('canvas'),ctx=canvas.getContext('2d'),scoreEl=content.querySelector('.snake-score'),start=content.querySelector('.snake-start'),pause=content.querySelector('.snake-pause');let body,direction,next,food,score,level=1,running=false,paused=false,timer=null,ended=false;const directions={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
function feed(){const free=[];for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(!body.some(p=>p[0]===x&&p[1]===y))free.push([x,y]);food=free.length?free[Math.floor(Math.random()*free.length)]:null}
function draw(message){ctx.fillStyle='#18291b';ctx.fillRect(0,0,360,360);ctx.strokeStyle='#233b27';for(let n=0;n<=20;n++){ctx.beginPath();ctx.moveTo(n*18,0);ctx.lineTo(n*18,360);ctx.moveTo(0,n*18);ctx.lineTo(360,n*18);ctx.stroke()}body.forEach((p,i)=>{ctx.fillStyle=i?'#a5c774':'#e0f8a8';ctx.fillRect(p[0]*18+1,p[1]*18+1,16,16)});if(food){ctx.fillStyle='#ef9377';ctx.fillRect(food[0]*18+3,food[1]*18+3,12,12)}if(message){ctx.fillStyle='#07110ad9';ctx.fillRect(0,136,360,88);ctx.fillStyle='#e0f8a8';ctx.textAlign='center';ctx.font='bold 20px monospace';ctx.fillText(message,180,186)}}
function scheduleSnake(){clearInterval(timer);timer=setInterval(tick,Math.max(90,250-(level-1)*20))}
function reset(){clearInterval(timer);level=1;content.querySelector('.snake-level').textContent=1;body=[[8,10],[7,10],[6,10]];direction=next=[1,0];score=0;scoreEl.textContent=0;ended=false;feed();draw('PRÊT À JOUER');pause.disabled=true;running=false;paused=false;pause.textContent='Pause'}
function finish(win=false){window.retroSound?.(win?'win':'error');running=false;ended=true;clearInterval(timer);pause.disabled=true;start.textContent='Rejouer';state.el.querySelector('.statusbar').textContent=(win?'Bravo !':'Partie terminée.')+' Score : '+score;draw(win?'GAGNÉ !':'GAME OVER')}
function tick(){if(paused||state.minimized||activeId!=='snake'||$('#system-dialog').open)return;direction=next;const head=[body[0][0]+direction[0],body[0][1]+direction[1]],eat=food&&head[0]===food[0]&&head[1]===food[1],solid=eat?body:body.slice(0,-1);if(head.some(n=>n<0||n>=20)||solid.some(p=>p[0]===head[0]&&p[1]===head[1]))return finish();body.unshift(head);if(eat){window.retroSound?.('point');score++;scoreEl.textContent=score;feed();if(!food)return finish(true);const newLevel=1+Math.floor(score/5);if(newLevel!==level){level=newLevel;content.querySelector('.snake-level').textContent=level;state.el.querySelector('.statusbar').textContent='Niveau '+level+' · La vitesse augmente toutes les 5 pommes.';scheduleSnake()}}else body.pop();draw()}
function turn(name){const d=directions[name];if(d[0]!==-direction[0]||d[1]!==-direction[1])next=d}
function togglePause(){if(!running)return;paused=!paused;pause.textContent=paused?'Reprendre':'Pause';draw(paused?'PAUSE':null)}
start.onclick=()=>{reset();running=true;pause.disabled=false;start.textContent='Recommencer';state.el.querySelector('.statusbar').textContent='Mange les carrés rouges. Évite les murs et ta queue.';draw();scheduleSnake();canvas.focus()};pause.onclick=togglePause;canvas.addEventListener('keydown',e=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',z:'up',w:'up',q:'left',a:'left',s:'down',d:'right'};if(map[e.key]){e.preventDefault();turn(map[e.key])}if(e.code==='Space'){e.preventDefault();togglePause()}});content.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{turn(b.dataset.direction);canvas.focus()});state.cleanup=()=>clearInterval(timer);reset();state.el.querySelector('.statusbar').textContent='Snake · 20 × 20 · La partie s’arrête lorsque la fenêtre est inactive.'}
function memoryGame(content,state){content.innerHTML='<div class="arcade"><div class="arcade-score"><b>MEMORY</b><span>Coups : <strong class="memory-score">0</strong></span></div><div class="memory-grid" aria-label="Jeu de mémoire, 16 cartes"></div><div class="arcade-actions"><button class="memory-reset">Nouvelle partie</button></div><p class="arcade-help">Retrouve les huit paires d’icônes du bureau.</p><p class="memory-result" role="status"></p></div>';const grid=content.querySelector('.memory-grid');let cards,first=null,locked=false,moves=0,pairs=0,timeout;const symbols=['computer','folder','text','terminal','paint','mines','settings','contact'];
function reset(){clearTimeout(timeout);first=null;locked=false;moves=pairs=0;content.querySelector('.memory-score').textContent=0;content.querySelector('.memory-result').textContent='';cards=[...symbols,...symbols];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}grid.replaceChildren();cards.forEach((symbol,index)=>{const b=document.createElement('button');b.className='memory-card';b.setAttribute('aria-label','Carte '+(index+1)+', face cachée');b.innerHTML='<span class="card-back">?</span><span class="card-front">'+icon(symbol)+'</span>';b.onclick=()=>{if(locked||b.classList.contains('revealed')||b.classList.contains('matched'))return;b.classList.add('revealed');b.setAttribute('aria-label','Carte '+(index+1)+' : '+symbol);if(!first){first={b,symbol};return}moves++;content.querySelector('.memory-score').textContent=moves;const previous=first;first=null;if(previous.symbol===symbol){b.classList.add('matched');previous.b.classList.add('matched');pairs++;window.retroSound?.('point');if(pairs===8){content.querySelector('.memory-result').textContent='Bravo ! Toutes les paires en '+moves+' coups.';state.el.querySelector('.statusbar').textContent='Partie gagnée · '+moves+' coups'}}else{locked=true;timeout=setTimeout(()=>{for(const button of [b,previous.b]){button.classList.remove('revealed');button.setAttribute('aria-label','Carte '+([...grid.children].indexOf(button)+1)+', face cachée')}locked=false},850)}};grid.append(b)});state.el.querySelector('.statusbar').textContent='8 paires · Choisis deux cartes.'}content.querySelector('.memory-reset').onclick=reset;state.cleanup=()=>clearTimeout(timeout);reset()}


