'use strict';
for(const [id,title] of [['invaders','Bug Invaders'],['packet','Packet Runner']]){apps[id]={title:title+' — Arcade',icon:'terminal',width:600,height:570};const b=document.createElement('button');b.className='desktop-icon';b.setAttribute('aria-label','Ouvrir '+title);b.innerHTML=icon('terminal')+'<span>'+title+'</span>';b.onclick=e=>{if(e.detail===0||matchMedia('(pointer:coarse)').matches)openApp(id)};b.ondblclick=()=>openApp(id);$('#icons').append(b);const m=document.createElement('button');m.dataset.open=id;m.innerHTML=icon('terminal')+title;$('#start-menu .start-items').insertBefore(m,$('#sleep'))}
const networkRender=renderApp;
renderApp=function(id,content,state){if(id==='invaders'||id==='packet')networkGame(id,content,state);else networkRender(id,content,state)};
function networkGame(id,content,state){
const shooter=id==='invaders';
content.innerHTML='<div class="arcade"><div class="arcade-score"><b>'+ (shooter?'BUG INVADERS':'PACKET RUNNER')+'</b><span class="network-score"></span></div><canvas class="network-board" width="480" height="340" tabindex="0" aria-label="'+(shooter?'Flèches gauche droite pour déplacer, espace pour tirer':'Flèches pour guider le paquet vers le serveur, collecte les clés')+'"></canvas><div class="arcade-actions"><button class="network-start">Jouer</button><button class="network-pause" disabled>Pause</button></div><div class="network-controls">'+(shooter?'<div><button data-key="left" aria-label="Gauche">←</button><button data-key="right" aria-label="Droite">→</button></div><button data-key="fire">Tirer ●</button>':'<div><button data-key="up" aria-label="Haut">↑</button><div><button data-key="left" aria-label="Gauche">←</button><button data-key="down" aria-label="Bas">↓</button><button data-key="right" aria-label="Droite">→</button></div></div>')+'</div><p class="arcade-help">'+(shooter?'← → : déplacement · Espace : tir · P : pause<br>Les bugs violets se divisent. Les rouges bloquent le tir.':'Flèches / ZQSD : déplacement · P : pause<br>Récupère les trois clés puis rejoins le serveur en haut à droite.')+'</p></div>';
const canvas=content.querySelector('canvas'),ctx=canvas.getContext('2d'),scoreEl=content.querySelector('.network-score'),pause=content.querySelector('.network-pause');let player,keys={},level,score,lives,running=false,paused=false,timer=0,last=0,frame,bullets,enemies,items,cooldown=0,blocked=0,immune=0,phase=0,ended=false;
const walls=[{x:100,y:70,w:18,h:190},{x:215,y:0,w:18,h:230},{x:335,y:110,w:18,h:230}];
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function loadLevel(){player={x:shooter?228:22,y:shooter?300:300,w:shooter?24:14,h:shooter?18:14};bullets=[];cooldown=blocked=immune=phase=0;keys={};if(shooter){enemies=[];for(let row=0;row<3;row++)for(let col=0;col<7;col++)enemies.push({x:48+col*52,y:38+row*35,w:22,h:18,type:row===0?'split':row===1?'jam':'normal',vx:1})}else{items=[{x:55,y:35,w:12,h:12},{x:165,y:280,w:12,h:12},{x:285,y:40,w:12,h:12}];enemies=[{x:130,y:150,w:26,h:22,min:130,max:183,vx:1},{x:250,y:250,w:26,h:22,min:245,max:300,vx:-1},{x:365,y:75,w:26,h:22,min:360,max:440,vx:1}]}status('Niveau '+level+' · '+(shooter?'Élimine tous les bugs.':'Collecte les clés et atteins le serveur.'))}
function status(s){state.el.querySelector('.statusbar').textContent=s}
function reset(){level=1;score=0;lives=3;ended=false;running=paused=false;pause.disabled=true;pause.textContent='Pause';loadLevel();hud()}
function hud(){scoreEl.textContent='Niv. '+level+' · '+score+' pts · '+lives+' vies'}
function damage(){if(immune>0)return;window.retroSound?.('error');lives--;immune=1.5;hud();if(lives<=0){running=false;ended=true;pause.disabled=true;status('Partie terminée · '+score+' points.')}else if(!shooter){player.x=22;player.y=300}}
function win(){window.retroSound?.('win');score+=100;level++;loadLevel();hud()}
function update(dt){immune=Math.max(0,immune-dt);blocked=Math.max(0,blocked-dt);cooldown=Math.max(0,cooldown-dt);phase+=dt;const speed=shooter?240:150;let nx=player.x+((keys.right?1:0)-(keys.left?1:0))*speed*dt,ny=player.y+(!shooter?((keys.down?1:0)-(keys.up?1:0))*speed*dt:0);nx=Math.max(0,Math.min(480-player.w,nx));ny=Math.max(0,Math.min(340-player.h,ny));if(shooter||!walls.some(w=>hit({...player,x:nx},w)))player.x=nx;if(shooter||!walls.some(w=>hit({...player,y:ny},w)))player.y=ny;
if(shooter){if(keys.fire&&cooldown===0&&blocked===0){window.retroSound?.('shoot');bullets.push({x:player.x+10,y:player.y,w:4,h:10});cooldown=.2}for(const b of bullets)b.y-=340*dt;for(const e of enemies){e.x+=e.vx*(12+level*5)*dt;if(e.x<6||e.x+e.w>474){e.vx*=-1;e.y+=12}e.y+=(2+level)*dt;if(e.y+e.h>=player.y){damage();if(!running)return;e.y=30}if(hit(e,player))damage()}for(const b of bullets){if(b.dead)continue;const e=enemies.find(e=>!e.dead&&hit(b,e));if(e){e.dead=b.dead=true;score+=10;if(e.type==='jam'){blocked=1.5;status('Erreur ! Tir bloqué pendant 1,5 seconde.')}if(e.type==='split')for(const vx of [-1,1])enemies.push({x:e.x+vx*10,y:e.y,w:12,h:12,vx,type:'normal'})}}bullets=bullets.filter(b=>!b.dead&&b.y>-12);enemies=enemies.filter(e=>!e.dead);if(!enemies.length)win()}else{for(const e of enemies){e.x+=e.vx*(45+level*9)*dt;if(e.x<e.min||e.x>e.max){e.x=Math.max(e.min,Math.min(e.max,e.x));e.vx*=-1}if(hit(player,e))damage()}for(const key of items)if(!key.taken&&hit(player,key)){key.taken=true;window.retroSound?.('point');score+=25;status('Clé récupérée · '+items.filter(k=>k.taken).length+' / 3')}if(player.x>430&&player.y<38){if(items.every(k=>k.taken))win();else status('Serveur verrouillé : récupère les trois clés.')}}hud()}
function draw(){ctx.fillStyle='#142b30';ctx.fillRect(0,0,480,340);ctx.strokeStyle='#25454a';for(let x=0;x<480;x+=24){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,340);ctx.stroke()}for(let y=0;y<340;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(480,y);ctx.stroke()}if(!shooter){ctx.fillStyle='#ab7053';for(const w of walls){ctx.fillRect(w.x,w.y,w.w,w.h);ctx.fillStyle='#e4a47e';for(let y=w.y+4;y<w.y+w.h;y+=14)ctx.fillRect(w.x+4,y,10,3);ctx.fillStyle='#ab7053'}ctx.fillStyle=items.every(k=>k.taken)?'#98c887':'#6c7b80';ctx.fillRect(432,5,42,34);ctx.fillStyle='#102d28';ctx.font='10px monospace';ctx.fillText('SRV',438,26);for(const k of items)if(!k.taken){ctx.fillStyle='#e5ca77';ctx.fillRect(k.x,k.y,8,8);ctx.fillRect(k.x+6,k.y+5,9,3)}}for(const e of enemies){ctx.fillStyle=e.type==='split'?'#b497d1':e.type==='jam'?'#df9585':'#87b69b';if(!shooter)ctx.fillStyle='#df9585';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#142b30';ctx.fillRect(e.x+4,e.y+4,4,4);ctx.fillRect(e.x+e.w-8,e.y+4,4,4)}ctx.fillStyle='#efdb9b';for(const b of bullets)ctx.fillRect(b.x,b.y,b.w,b.h);if(immune===0||Math.floor(phase*10)%2===0){ctx.fillStyle=blocked>0?'#d78473':'#c3d9dc';ctx.fillRect(player.x,player.y,player.w,player.h);ctx.fillStyle='#517986';ctx.fillRect(player.x+4,player.y+4,player.w-8,5)}if(!running||paused){ctx.fillStyle='#07151ee8';ctx.fillRect(40,116,400,100);ctx.textAlign='center';ctx.fillStyle='#e6e3c8';ctx.font='bold 24px monospace';ctx.fillText(paused?'PAUSE':ended?'GAME OVER':shooter?'BUG INVADERS':'PACKET RUNNER',240,157);ctx.font='13px monospace';ctx.fillText(ended?'Rejoue pour battre ton score':'Clique sur Jouer',240,188);ctx.textAlign='left'}if(blocked>0&&running){ctx.fillStyle='#ffd4c5';ctx.font='12px monospace';ctx.fillText('TIR BLOQUÉ '+blocked.toFixed(1)+'s',12,330)}}
const clear=()=>{keys={};content.querySelectorAll('[data-key]').forEach(b=>b.classList.remove('held'))};const toggle=()=>{if(!running)return;paused=!paused;clear();pause.textContent=paused?'Reprendre':'Pause'};
content.querySelector('.network-start').onclick=()=>{reset();running=true;pause.disabled=false;content.querySelector('.network-start').textContent='Rejouer';canvas.focus()};pause.onclick=toggle;const keyMap={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',q:'left',a:'left',d:'right',z:'up',w:'up',s:'down',' ':'fire'};canvas.onkeydown=e=>{if(keyMap[e.key]){e.preventDefault();keys[keyMap[e.key]]=true}if(e.key.toLowerCase()==='p'&&!e.repeat)toggle()};canvas.onkeyup=e=>{if(keyMap[e.key]){e.preventDefault();keys[keyMap[e.key]]=false}};canvas.onblur=clear;content.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;b.classList.add('held')};const release=()=>{keys[b.dataset.key]=false;b.classList.remove('held')};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release});function loop(time){const dt=Math.min((time-last)/1000,.03);last=time;if(running&&!paused&&!state.minimized&&activeId===id&&!$('#system-dialog').open)update(dt);else clear();draw();frame=requestAnimationFrame(loop)}reset();frame=requestAnimationFrame(loop);state.cleanup=()=>cancelAnimationFrame(frame)
}

