'use strict';
apps.platformer={title:'Super Dev — Plateforme',icon:'paint',width:720,height:530};
const platformRender=renderApp;
renderApp=function(id,content,state){if(id==='platformer')platformGame(content,state);else platformRender(id,content,state)};
{const b=document.createElement('button');b.className='desktop-icon';b.setAttribute('aria-label','Ouvrir Super Dev');b.innerHTML=icon('paint')+'<span>Super Dev</span>';b.onclick=e=>{if(e.detail===0||matchMedia('(pointer:coarse)').matches)openApp('platformer')};b.ondblclick=()=>openApp('platformer');$('#icons').append(b);const m=document.createElement('button');m.dataset.open='platformer';m.innerHTML=icon('paint')+'Super Dev';$('#start-menu .start-items').insertBefore(m,$('#sleep'))}
function platformGame(content,state){
content.innerHTML='<div class="arcade"><div class="arcade-score"><b>SUPER DEV · <span class="platform-level">NIVEAU 1</span></b><span class="platform-score"></span></div><canvas width="640" height="320" class="platform-board" tabindex="0" aria-label="Jeu de plateforme. Flèches ou Q D pour marcher. Espace ou flèche haut pour sauter. P pour pause."></canvas><div class="arcade-actions"><button class="platform-start">Jouer</button><button class="platform-pause" disabled>Pause</button><button class="platform-next" hidden>Niveau suivant →</button><button class="platform-secret" hidden>Entrer dans le tunnel ↓</button></div><div class="platform-pad"><button data-key="left" aria-label="Marcher à gauche">←</button><button data-key="right" aria-label="Marcher à droite">→</button><button data-key="jump">Sauter ↑</button></div><p class="arcade-help">← → / Q D : marcher · Espace / ↑ : sauter · P : pause<br>Saute sur les robots, ramasse les pièces et rejoins le drapeau.</p></div>';
const canvas=content.querySelector('canvas'),ctx=canvas.getContext('2d'),pause=content.querySelector('.platform-pause'),scoreEl=content.querySelector('.platform-score');
const baseTerrain=[{x:0,y:280,w:480,h:40},{x:570,y:280,w:460,h:40},{x:1120,y:280,w:500,h:40},{x:1710,y:280,w:490,h:40},{x:240,y:207,w:110,h:18},{x:685,y:200,w:130,h:18},{x:930,y:150,w:110,h:18},{x:1230,y:205,w:130,h:18},{x:1510,y:165,w:130,h:18},{x:1830,y:205,w:120,h:18}];
let gateOpen=false,levelTime=0,lasers=[],switchPad=null,blocks=[],shield=false,bonusRoom=false,returnPoint=null,bonusCollected=0,terrain,moving=[],level=1,checkpoint=40,transition=false,player,coins,enemies,keys={},running=false,paused=false,ended=false,won=false,lives=3,score=0,camera=0,last=0,frame,invincible=0,coyote=0,jumpBuffer=0;
let bonusCoins=[];
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function loadLevel(){
gateOpen=level===1;levelTime=0;lasers=[];switchPad=null;
if(level===1){terrain=[{x:0,y:280,w:540,h:40},{x:600,y:280,w:580,h:40},{x:1240,y:280,w:960,h:40},{x:270,y:210,w:120,h:18},{x:760,y:200,w:140,h:18},{x:1470,y:205,w:150,h:18}];moving=[]}
if(level===2){terrain=[{x:0,y:280,w:420,h:40},{x:480,y:230,w:260,h:90},{x:810,y:175,w:240,h:145},{x:1120,y:230,w:320,h:90},{x:1510,y:280,w:690,h:40},{x:1650,y:200,w:150,h:18}];terrain[1].belt=1;terrain[3].belt=-1;moving=[{x:745,y:240,w:60,h:14,origin:745,originY:240,phase:0,dx:0,dy:0,vertical:true}];switchPad={x:985,y:155,w:25,h:20}}
if(level===3){terrain=[{x:0,y:280,w:420,h:40},{x:620,y:260,w:240,h:60},{x:1080,y:280,w:270,h:40},{x:1560,y:260,w:280,h:60},{x:1940,y:280,w:260,h:40},{x:470,y:245,w:100,h:16,temporary:true,life:55},{x:910,y:225,w:110,h:16,temporary:true,life:55},{x:1410,y:235,w:95,h:16,temporary:true,life:55},{x:1870,y:220,w:65,h:16,temporary:true,life:55}];moving=[];lasers=[{x:740,y:210,w:10,h:50},{x:1200,y:220,w:10,h:60},{x:1670,y:200,w:10,h:60}];switchPad={x:2040,y:258,w:30,h:22}}
blocks=[{x:380,y:175,w:28,h:28,used:false,reward:'coin'},{x:760,y:150,w:28,h:28,used:false,reward:'shield'}];terrain.push(...moving,...blocks);shield=false;bonusRoom=false;bonusCoins=[];bonusCollected=0;returnPoint=null;checkpoint=40;
player={x:40,y:220,w:22,h:30,vx:0,vy:0,ground:false};coins=[280,320,720,770,970,1260,1310,1550,1590,1860,1910,2050].map((x,i)=>({x,y:[175,175,168,168,118,173,173,133,133,173,173,240][i],w:12,h:16,taken:false}));enemies=[{x:350,y:258,w:24,h:22,left:320,right:440,vx:1.1},{x:840,y:258,w:24,h:22,left:820,right:970,vx:1.2},{x:1390,y:258,w:24,h:22,left:1370,right:1540,vx:1.3},{x:1960,y:258,w:24,h:22,left:1955,right:2110,vx:1.4}];if(level===1)enemies=[{x:370,y:258,w:24,h:22,left:350,right:480,vx:.9},{x:1550,y:258,w:24,h:22,left:1520,right:1730,vx:1}];
if(level===2)enemies=[{x:550,y:208,w:24,h:22,left:500,right:700,vx:1.1},{x:1190,y:208,w:24,h:22,left:1150,right:1380,vx:1.2},{x:1850,y:258,w:24,h:22,left:1800,right:1990,vx:1.2}];
if(level===3)enemies=[{x:1120,y:258,w:24,h:22,left:1100,right:1310,vx:1.25},{x:1760,y:238,w:24,h:22,left:1720,right:1800,vx:1.3}];
coins=terrain.filter(t=>!t.temporary).flatMap(t=>[.3,.65].map(r=>({x:t.x+t.w*r,y:t.y-30,w:12,h:16,taken:false})));
keys={};camera=0;invincible=0;coyote=jumpBuffer=0;content.querySelector('.platform-secret').hidden=true;content.querySelector('.platform-secret').textContent='Entrer dans le tunnel ↓';transition=ended=won=false;content.querySelector('.platform-level').textContent='NIVEAU '+level+' / 3';updateScore()}
function reset(){level=1;lives=5;score=0;running=paused=false;pause.disabled=true;pause.textContent='Pause';content.querySelector('.platform-next').hidden=true;loadLevel()}
function updateScore(){scoreEl.textContent=score+' pièces · '+lives+' vies'}
function hurt(){if(invincible>0)return;if(shield){shield=false;invincible=120;window.retroSound?.('point');state.el.querySelector('.statusbar').textContent='Bouclier utilisé · Un coup absorbé.';return}window.retroSound?.('error');lives--;updateScore();if(lives<=0){running=false;ended=true;pause.disabled=true;state.el.querySelector('.statusbar').textContent='Partie terminée. Rejoue pour atteindre le drapeau.'}else{player.x=checkpoint;const respawnFloor=terrain.find(t=>!t.gone&&checkpoint>=t.x&&checkpoint+player.w<=t.x+t.w&&t.h>=40);player.y=(respawnFloor?respawnFloor.y:280)-player.h;player.vx=player.vy=0;invincible=120;player.ground=false;coyote=jumpBuffer=0;keys={}}}
function consumeJump(){if(jumpBuffer>0&&(player.ground||coyote>0)){window.retroSound?.('jump');player.vy=-10.8;player.ground=false;coyote=jumpBuffer=0}}
function jump(){if(!running||paused)return;jumpBuffer=8;consumeJump()}
function toggle(){if(!running)return;paused=!paused;keys={};jumpBuffer=0;pause.textContent=paused?'Reprendre':'Pause';canvas.focus()}
function step(dt){if(!bonusRoom){levelTime+=dt;for(const t of terrain){if(t.gone){t.recover-=dt;if(t.recover<=0){t.gone=false;t.life=55}}else if(t.temporary&&player.ground&&Math.abs(player.y+player.h-t.y)<1&&player.x+player.w>t.x&&player.x<t.x+t.w){t.life-=dt;if(t.life<=0){t.gone=true;t.recover=150}}if(t.belt&&player.ground&&Math.abs(player.y+player.h-t.y)<1&&player.x+player.w>t.x&&player.x<t.x+t.w)player.x+=t.belt*.8*dt}}
for(const t of moving){const old=t.x;t.phase+=dt*.018;const oldY=t.y;if(t.vertical)t.y=t.originY+Math.sin(t.phase)*45;else t.x=t.origin+Math.sin(t.phase)*25;t.dx=t.x-old;t.dy=t.y-oldY;if(player.ground&&Math.abs(player.y+player.h-oldY)<1&&player.x+player.w>old&&player.x<old+t.w) {player.x+=t.dx;player.y+=t.dy||0}}
coyote=player.ground?7:Math.max(0,coyote-dt);jumpBuffer=Math.max(0,jumpBuffer-dt);consumeJump();invincible=Math.max(0,invincible-dt);player.vx=((keys.right?1:0)-(keys.left?1:0))*3.4;player.x+=player.vx*dt;for(const t of terrain)if(!t.gone&&overlap(player,t)){if(player.vx>0)player.x=t.x-player.w;else if(player.vx<0)player.x=t.x+t.w}player.x=Math.max(0,Math.min(2178,player.x));const previousY=player.y;player.vy=Math.min(12,player.vy+.48*dt);player.y+=player.vy*dt;player.ground=false;for(const t of terrain)if(overlap(player,t)){if(player.vy>=0&&previousY+player.h<=t.y+1){player.y=t.y-player.h;player.vy=0;player.ground=true}else if(player.vy<0&&previousY>=t.y+t.h-1){player.y=t.y+t.h;player.vy=0;if(blocks.includes(t)&&!t.used){t.used=true;if(t.reward==='shield'){shield=true;window.retroSound?.('win');state.el.querySelector('.statusbar').textContent='Bouclier obtenu · Protège contre un robot, pas contre les trous.'}else{score+=5;window.retroSound?.('point')}updateScore()}}}
consumeJump();if(!bonusRoom){if(switchPad&&overlap(player,switchPad)&&!gateOpen){gateOpen=true;window.retroSound?.('win');state.el.querySelector('.statusbar').textContent=level===2?'Interrupteur activé · Sortie ouverte !':'Serveur désactivé · Rejoins la sortie !'}for(const laser of lasers)if(Math.floor(levelTime/90)%2===1&&overlap(player,laser))hurt()}if(bonusRoom){for(const c of bonusCoins)if(!c.taken&&overlap(player,c)){c.taken=true;score++;bonusCollected++;window.retroSound?.('point');updateScore()}if(player.y>360){player.x=40;player.y=220}content.querySelector('.platform-secret').hidden=false;content.querySelector('.platform-secret').textContent='Retour au niveau →';camera=0;return}content.querySelector('.platform-secret').hidden=!(player.x>870&&player.x<1010);for(const x of [650,1200,1800])if(player.x>x&&checkpoint<x&&player.ground){checkpoint=x;window.retroSound?.('point');state.el.querySelector('.statusbar').textContent='Checkpoint activé · Tu reprendras ici après une chute.'}if(player.y>360){invincible=0;shield=false;hurt();return}for(const c of coins)if(!c.taken&&overlap(player,c)){c.taken=true;window.retroSound?.('point');score++;updateScore()}for(const e of enemies){if(e.dead)continue;e.x+=e.vx*dt;if(e.x<e.left||e.x>e.right)e.vx*=-1;if(overlap(player,e)){if(player.vy>0&&previousY+player.h<=e.y+8){e.dead=true;player.vy=-7.5;player.ground=false;coyote=jumpBuffer=0}else hurt()}}
if(player.x>2120&&!gateOpen){state.el.querySelector('.statusbar').textContent=level===2?'Sortie verrouillée : active l’interrupteur sur la plateforme haute.':'Désactive le serveur avant de sortir.';player.x=2120}if(player.x>2120&&gateOpen){won=true;transition=level<3;ended=!transition;running=false;pause.disabled=true;keys={};window.retroSound?.('win');content.querySelector('.platform-next').hidden=!transition;state.el.querySelector('.statusbar').textContent=transition?'Niveau réussi · Passe au suivant !':'Bravo ! Les trois niveaux sont terminés.'}camera=Math.max(0,Math.min(1560,player.x-250))}
function draw(){ctx.fillStyle=['#83bad0','#9299ad','#789c99'][level-1];ctx.fillRect(0,0,640,320);ctx.fillStyle='#d6e9e8';for(let n=0;n<8;n++){const cx=n*270-camera*.35;ctx.fillRect(cx,48+(n%2)*30,70,18);ctx.fillRect(cx+17,38+(n%2)*30,36,18)}ctx.fillStyle='#689c98';for(let n=0;n<7;n++){const cx=n*340-camera*.5;ctx.beginPath();ctx.moveTo(cx-70,280);ctx.lineTo(cx+70,130);ctx.lineTo(cx+210,280);ctx.fill()}
ctx.save();ctx.translate(-Math.floor(camera),0);if(bonusRoom){ctx.fillStyle='#243d54';ctx.fillRect(0,0,640,320);ctx.fillStyle='#d6dcac';ctx.font='16px monospace';ctx.fillText('CACHE SECRÈTE / '+bonusCollected+' pièces',25,45)}for(const t of terrain){if(t.gone)continue;ctx.fillStyle=moving.includes(t)?'#4b6776':'#765e4b';ctx.fillRect(t.x,t.y,t.w,t.h);ctx.fillStyle=t.temporary?'#d5ab73':t.belt?'#b1a6ca':'#8da66b';ctx.fillRect(t.x,t.y,t.w,6);ctx.fillStyle='#a08062';for(let x=t.x+6;x<t.x+t.w;x+=24)ctx.fillRect(x,t.y+12,16,3)}for(const c of (bonusRoom?bonusCoins:coins))if(!c.taken){ctx.fillStyle='#f0ce69';ctx.fillRect(c.x,c.y,12,16);ctx.fillStyle='#fff1af';ctx.fillRect(c.x+3,c.y+3,3,9)}for(const e of (bonusRoom?[]:enemies))if(!e.dead){ctx.fillStyle='#655c77';ctx.fillRect(e.x,e.y,e.w,e.h-4);ctx.fillStyle='#ebe3d5';ctx.fillRect(e.x+4,e.y+4,5,5);ctx.fillRect(e.x+15,e.y+4,5,5);ctx.fillStyle='#333147';ctx.fillRect(e.x-2,e.y+18,10,4);ctx.fillRect(e.x+16,e.y+18,10,4)}for(const x of [650,1200,1800]){ctx.fillStyle=x<=checkpoint?'#a6d081':'#c9c7b4';ctx.fillRect(x,243,3,37);ctx.fillRect(x+3,243,20,12)}if(!bonusRoom){for(const laser of lasers){ctx.fillStyle=Math.floor(levelTime/90)%2===1?'#ff7777':'#813f4c';ctx.fillRect(laser.x,laser.y,laser.w,laser.h)}if(switchPad){ctx.fillStyle=gateOpen?'#acd390':'#e4af6c';ctx.fillRect(switchPad.x,switchPad.y,switchPad.w,switchPad.h);ctx.fillStyle='#152b2c';ctx.font='10px monospace';ctx.fillText(level===2?'ON':'OFF',switchPad.x,switchPad.y-5)}}for(const b of blocks){ctx.fillStyle=b.used?'#8c806b':b.reward==='shield'?'#bfc990':'#e7b867';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#604b3b';ctx.strokeRect(b.x+2,b.y+2,b.w-4,b.h-4);ctx.fillStyle='#3b3f32';ctx.font='bold 20px monospace';ctx.fillText(b.used?'·':'?',b.x+7,b.y+22)}if(!bonusRoom){ctx.fillStyle='#3e6358';ctx.fillRect(930,245,42,35);ctx.fillStyle='#192f2d';ctx.fillRect(939,251,24,29);ctx.fillStyle='#f1deb0';ctx.font='10px monospace';ctx.fillText('↓',947,245)}ctx.fillStyle='#ddd8c8';ctx.fillRect(2140,140,4,140);ctx.fillStyle='#315e65';ctx.fillRect(2144,142,38,24);ctx.fillStyle='#eee';ctx.font='12px monospace';ctx.fillText('</>',2148,159);
if(invincible<=0||Math.floor(invincible/6)%2===0){const p=player;if(shield){ctx.strokeStyle='#fff0a7';ctx.lineWidth=2;ctx.strokeRect(p.x-5,p.y-5,p.w+10,p.h+10)}ctx.fillStyle='#364d65';ctx.fillRect(p.x+3,p.y+18,16,9);ctx.fillStyle='#d68d55';ctx.fillRect(p.x+1,p.y+11,20,10);ctx.fillStyle='#edd0a4';ctx.fillRect(p.x+5,p.y+3,14,10);ctx.fillStyle='#315e65';ctx.fillRect(p.x+3,p.y,17,5);ctx.fillStyle='#23343b';ctx.fillRect(p.x+15,p.y+6,3,3);ctx.fillRect(p.x,p.y+26,10,4);ctx.fillRect(p.x+13,p.y+26,10,4)}ctx.restore();if(!running||paused){ctx.fillStyle='#132b36df';ctx.fillRect(95,100,450,105);ctx.fillStyle='#f4e9d3';ctx.textAlign='center';ctx.font='bold 24px monospace';ctx.fillText(paused?'PAUSE':won?'NIVEAU RÉUSSI !':ended?'GAME OVER':'SUPER DEV',320,143);ctx.font='14px monospace';ctx.fillText(won?(transition?'Clique sur Niveau suivant':'Trois niveaux terminés · '+score+' pièces'):ended?'Clique sur Rejouer':'Un petit voyage jusqu’au drapeau',320,175)}}
content.querySelector('.platform-start').onclick=()=>{reset();running=true;pause.disabled=false;content.querySelector('.platform-start').textContent='Rejouer';state.el.querySelector('.statusbar').textContent='5 vies · Niveau 1 : apprentissage · Pause automatique hors de la fenêtre';canvas.focus()};pause.onclick=toggle;content.querySelector('.platform-secret').onclick=()=>{if(!running||paused)return;if(!bonusRoom){returnPoint={x:player.x,y:player.y,terrain,coins,enemies,blocks,moving};bonusRoom=true;if(!bonusCoins.length)bonusCoins=Array.from({length:8},(_,i)=>({x:105+i*48,y:240,w:12,h:16,taken:false}));terrain=[{x:0,y:280,w:640,h:40}];blocks=[];moving=[];player.x=40;player.y=220;camera=0;state.el.querySelector('.statusbar').textContent='Salle secrète · Collecte les pièces, puis reviens au niveau.'}else{({terrain,coins,enemies,blocks,moving}=returnPoint);player.x=returnPoint.x;player.y=returnPoint.y;bonusRoom=false;returnPoint=null;content.querySelector('.platform-secret').textContent='Entrer dans le tunnel ↓';state.el.querySelector('.statusbar').textContent='De retour · '+bonusCollected+' pièces bonus récupérées.'}player.vx=player.vy=0;player.ground=false;coyote=jumpBuffer=0;keys={};canvas.focus()};content.querySelector('.platform-next').onclick=()=>{level++;lives=Math.min(5,lives+1);loadLevel();running=true;pause.disabled=false;content.querySelector('.platform-next').hidden=true;state.el.querySelector('.statusbar').textContent=level===2?'Usine · Tapis roulants, ascenseur et interrupteur en hauteur.':'Serveurs · Plateformes fragiles, lasers intermittents et serveur à désactiver.';canvas.focus()};
const map={ArrowLeft:'left',q:'left',a:'left',ArrowRight:'right',d:'right'};canvas.onkeydown=e=>{if(map[e.key]){e.preventDefault();keys[map[e.key]]=true}if(e.code==='Space'||e.key==='ArrowUp'||e.key==='z'||e.key==='w'){e.preventDefault();if(!e.repeat)jump()}if(e.key.toLowerCase()==='p'&&!e.repeat)toggle()};canvas.onkeyup=e=>{if(map[e.key]){e.preventDefault();keys[map[e.key]]=false}};canvas.onblur=()=>{keys={};jumpBuffer=0};
content.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.key==='jump')jump();else keys[b.dataset.key]=true};const release=()=>{keys[b.dataset.key]=false};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;b.onclick=e=>{if(e.detail===0&&b.dataset.key==='jump')jump()}});
function loop(time){const dt=Math.min((time-last)/16.667,2);last=time;if(running&&!paused&&!state.minimized&&activeId==='platformer'&&!$('#system-dialog').open)step(dt);else{keys={};jumpBuffer=0}draw();frame=requestAnimationFrame(loop)}reset();frame=requestAnimationFrame(loop);state.cleanup=()=>cancelAnimationFrame(frame)
}




