'use strict';
apps.platformer={title:'Super Dev — Plateforme',icon:'paint',width:720,height:530};
const platformRender=renderApp;
renderApp=function(id,content,state){if(id==='platformer')platformGame(content,state);else platformRender(id,content,state)};
{const b=document.createElement('button');b.className='desktop-icon';b.setAttribute('aria-label','Ouvrir Super Dev');b.innerHTML=icon('paint')+'<span>Super Dev</span>';b.onclick=e=>{if(e.detail===0||matchMedia('(pointer:coarse)').matches)openApp('platformer')};b.ondblclick=()=>openApp('platformer');$('#icons').append(b);const m=document.createElement('button');m.dataset.open='platformer';m.innerHTML=icon('paint')+'Super Dev';$('#start-menu .start-items').insertBefore(m,$('#sleep'))}
function platformGame(content,state){
content.innerHTML='<div class="arcade"><div class="arcade-score"><b>SUPER DEV · WORLD 01</b><span class="platform-score"></span></div><canvas width="640" height="320" class="platform-board" tabindex="0" aria-label="Jeu de plateforme. Flèches ou Q D pour marcher. Espace ou flèche haut pour sauter. P pour pause."></canvas><div class="arcade-actions"><button class="platform-start">Jouer</button><button class="platform-pause" disabled>Pause</button></div><div class="platform-pad"><button data-key="left" aria-label="Marcher à gauche">←</button><button data-key="right" aria-label="Marcher à droite">→</button><button data-key="jump">Sauter ↑</button></div><p class="arcade-help">← → / Q D : marcher · Espace / ↑ : sauter · P : pause<br>Saute sur les robots, ramasse les pièces et rejoins le drapeau.</p></div>';
const canvas=content.querySelector('canvas'),ctx=canvas.getContext('2d'),pause=content.querySelector('.platform-pause'),scoreEl=content.querySelector('.platform-score');
const terrain=[{x:0,y:280,w:480,h:40},{x:570,y:280,w:460,h:40},{x:1120,y:280,w:500,h:40},{x:1710,y:280,w:490,h:40},{x:240,y:207,w:110,h:18},{x:685,y:200,w:130,h:18},{x:930,y:150,w:110,h:18},{x:1230,y:205,w:130,h:18},{x:1510,y:165,w:130,h:18},{x:1830,y:205,w:120,h:18}];
let player,coins,enemies,keys={},running=false,paused=false,ended=false,won=false,lives=3,score=0,camera=0,last=0,frame,invincible=0,coyote=0,jumpBuffer=0;
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function reset(){player={x:40,y:220,w:22,h:30,vx:0,vy:0,ground:false};coins=[280,320,720,770,970,1260,1310,1550,1590,1860,1910,2050].map((x,i)=>({x,y:[175,175,168,168,118,173,173,133,133,173,173,240][i],w:12,h:16,taken:false}));enemies=[{x:350,y:258,w:24,h:22,left:320,right:440,vx:1.1},{x:840,y:258,w:24,h:22,left:820,right:970,vx:1.2},{x:1390,y:258,w:24,h:22,left:1370,right:1540,vx:1.3},{x:1960,y:258,w:24,h:22,left:1955,right:2110,vx:1.4}];keys={};lives=3;score=0;camera=0;invincible=0;coyote=jumpBuffer=0;running=paused=ended=won=false;pause.disabled=true;pause.textContent='Pause';updateScore()}
function updateScore(){scoreEl.textContent=score+' pièces · '+lives+' vies'}
function hurt(){if(invincible>0)return;window.retroSound?.('error');lives--;updateScore();if(lives<=0){running=false;ended=true;pause.disabled=true;state.el.querySelector('.statusbar').textContent='Partie terminée. Rejoue pour atteindre le drapeau.'}else{player.x=40;player.y=220;player.vx=player.vy=0;invincible=120;player.ground=false;coyote=jumpBuffer=0;keys={}}}
function consumeJump(){if(jumpBuffer>0&&(player.ground||coyote>0)){window.retroSound?.('jump');player.vy=-10.8;player.ground=false;coyote=jumpBuffer=0}}
function jump(){if(!running||paused)return;jumpBuffer=8;consumeJump()}
function toggle(){if(!running)return;paused=!paused;keys={};jumpBuffer=0;pause.textContent=paused?'Reprendre':'Pause';canvas.focus()}
function step(dt){coyote=player.ground?7:Math.max(0,coyote-dt);jumpBuffer=Math.max(0,jumpBuffer-dt);consumeJump();invincible=Math.max(0,invincible-dt);player.vx=((keys.right?1:0)-(keys.left?1:0))*3.4;player.x+=player.vx*dt;for(const t of terrain)if(overlap(player,t)){if(player.vx>0)player.x=t.x-player.w;else if(player.vx<0)player.x=t.x+t.w}player.x=Math.max(0,Math.min(2178,player.x));const previousY=player.y;player.vy=Math.min(12,player.vy+.48*dt);player.y+=player.vy*dt;player.ground=false;for(const t of terrain)if(overlap(player,t)){if(player.vy>=0&&previousY+player.h<=t.y+1){player.y=t.y-player.h;player.vy=0;player.ground=true}else if(player.vy<0&&previousY>=t.y+t.h-1){player.y=t.y+t.h;player.vy=0}}
consumeJump();if(player.y>360){invincible=0;hurt();return}for(const c of coins)if(!c.taken&&overlap(player,c)){c.taken=true;window.retroSound?.('point');score++;updateScore()}for(const e of enemies){if(e.dead)continue;e.x+=e.vx*dt;if(e.x<e.left||e.x>e.right)e.vx*=-1;if(overlap(player,e)){if(player.vy>0&&previousY+player.h<=e.y+8){e.dead=true;player.vy=-7.5;player.ground=false;coyote=jumpBuffer=0}else hurt()}}
if(player.x>2120){won=ended=true;running=false;pause.disabled=true;state.el.querySelector('.statusbar').textContent='Niveau réussi ! '+score+' / 12 pièces.'}camera=Math.max(0,Math.min(1560,player.x-250))}
function draw(){ctx.fillStyle='#83bad0';ctx.fillRect(0,0,640,320);ctx.fillStyle='#d6e9e8';for(let n=0;n<8;n++){const cx=n*270-camera*.35;ctx.fillRect(cx,48+(n%2)*30,70,18);ctx.fillRect(cx+17,38+(n%2)*30,36,18)}ctx.fillStyle='#689c98';for(let n=0;n<7;n++){const cx=n*340-camera*.5;ctx.beginPath();ctx.moveTo(cx-70,280);ctx.lineTo(cx+70,130);ctx.lineTo(cx+210,280);ctx.fill()}
ctx.save();ctx.translate(-Math.floor(camera),0);for(const t of terrain){ctx.fillStyle='#765e4b';ctx.fillRect(t.x,t.y,t.w,t.h);ctx.fillStyle='#8da66b';ctx.fillRect(t.x,t.y,t.w,6);ctx.fillStyle='#a08062';for(let x=t.x+6;x<t.x+t.w;x+=24)ctx.fillRect(x,t.y+12,16,3)}for(const c of coins)if(!c.taken){ctx.fillStyle='#f0ce69';ctx.fillRect(c.x,c.y,12,16);ctx.fillStyle='#fff1af';ctx.fillRect(c.x+3,c.y+3,3,9)}for(const e of enemies)if(!e.dead){ctx.fillStyle='#655c77';ctx.fillRect(e.x,e.y,e.w,e.h-4);ctx.fillStyle='#ebe3d5';ctx.fillRect(e.x+4,e.y+4,5,5);ctx.fillRect(e.x+15,e.y+4,5,5);ctx.fillStyle='#333147';ctx.fillRect(e.x-2,e.y+18,10,4);ctx.fillRect(e.x+16,e.y+18,10,4)}ctx.fillStyle='#ddd8c8';ctx.fillRect(2140,140,4,140);ctx.fillStyle='#315e65';ctx.fillRect(2144,142,38,24);ctx.fillStyle='#eee';ctx.font='12px monospace';ctx.fillText('</>',2148,159);
if(invincible<=0||Math.floor(invincible/6)%2===0){const p=player;ctx.fillStyle='#364d65';ctx.fillRect(p.x+3,p.y+18,16,9);ctx.fillStyle='#d68d55';ctx.fillRect(p.x+1,p.y+11,20,10);ctx.fillStyle='#edd0a4';ctx.fillRect(p.x+5,p.y+3,14,10);ctx.fillStyle='#315e65';ctx.fillRect(p.x+3,p.y,17,5);ctx.fillStyle='#23343b';ctx.fillRect(p.x+15,p.y+6,3,3);ctx.fillRect(p.x,p.y+26,10,4);ctx.fillRect(p.x+13,p.y+26,10,4)}ctx.restore();if(!running||paused){ctx.fillStyle='#132b36df';ctx.fillRect(95,100,450,105);ctx.fillStyle='#f4e9d3';ctx.textAlign='center';ctx.font='bold 24px monospace';ctx.fillText(paused?'PAUSE':won?'NIVEAU RÉUSSI !':ended?'GAME OVER':'SUPER DEV',320,143);ctx.font='14px monospace';ctx.fillText(won?score+' / 12 pièces récoltées':ended?'Clique sur Rejouer':'Un petit voyage jusqu’au drapeau',320,175)}}
content.querySelector('.platform-start').onclick=()=>{reset();running=true;pause.disabled=false;content.querySelector('.platform-start').textContent='Rejouer';state.el.querySelector('.statusbar').textContent='3 vies · Attention aux trous · Pause automatique hors de la fenêtre';canvas.focus()};pause.onclick=toggle;
const map={ArrowLeft:'left',q:'left',a:'left',ArrowRight:'right',d:'right'};canvas.onkeydown=e=>{if(map[e.key]){e.preventDefault();keys[map[e.key]]=true}if(e.code==='Space'||e.key==='ArrowUp'||e.key==='z'||e.key==='w'){e.preventDefault();if(!e.repeat)jump()}if(e.key.toLowerCase()==='p'&&!e.repeat)toggle()};canvas.onkeyup=e=>{if(map[e.key]){e.preventDefault();keys[map[e.key]]=false}};canvas.onblur=()=>{keys={};jumpBuffer=0};
content.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.key==='jump')jump();else keys[b.dataset.key]=true};const release=()=>{keys[b.dataset.key]=false};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;b.onclick=e=>{if(e.detail===0&&b.dataset.key==='jump')jump()}});
function loop(time){const dt=Math.min((time-last)/16.667,2);last=time;if(running&&!paused&&!state.minimized&&activeId==='platformer'&&!$('#system-dialog').open)step(dt);else{keys={};jumpBuffer=0}draw();frame=requestAnimationFrame(loop)}reset();frame=requestAnimationFrame(loop);state.cleanup=()=>cancelAnimationFrame(frame)
}


