'use strict';
apps.solitaire={title:'Solitaire — Klondike',icon:'computer',width:800,height:620};
const cardRender=renderApp;
renderApp=function(id,content,state){if(id==='solitaire')solitaireGame(content,state);else cardRender(id,content,state)};
{const b=document.createElement('button');b.className='desktop-icon';b.setAttribute('aria-label','Ouvrir Solitaire');b.innerHTML=icon('computer')+'<span>Solitaire</span>';b.onclick=e=>{if(e.detail===0||matchMedia('(pointer:coarse)').matches)openApp('solitaire')};b.ondblclick=()=>openApp('solitaire');$('#icons').append(b);const m=document.createElement('button');m.dataset.open='solitaire';m.textContent='Solitaire';$('#start-menu .start-items').insertBefore(m,$('#sleep'))}
function solitaireGame(content,state){
let stock,waste,foundations,columns,selected=null,history=[],moves=0;const suits=['♠','♥','♣','♦'];
const red=c=>c.suit===1||c.suit===3,rank=c=>['','A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.rank];
const save=()=>JSON.stringify({stock,waste,foundations,columns,moves});
function remember(){history.push(save());if(history.length>100)history.shift()}
function message(text){state.el.querySelector('.statusbar').textContent=text}
function reset(){const deck=[];for(let suit=0;suit<4;suit++)for(let value=1;value<=13;value++)deck.push({suit,rank:value,up:false});for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}columns=Array.from({length:7},(_,i)=>Array.from({length:i+1},(_,j)=>({...deck.pop(),up:j===i})));stock=deck;waste=[];foundations=[[],[],[],[]];history=[];moves=0;selected=null;render();message('Pioche une carte ou sélectionne une carte visible, puis sa destination.')}
function source(){if(!selected)return null;return selected.type==='waste'?waste:selected.type==='foundation'?foundations[selected.pile]:columns[selected.pile]}
function move(type,pile){const from=source();if(!from)return;const cards=from.slice(selected.index),card=cards[0],to=type==='foundation'?foundations[pile]:columns[pile];if(from===to){selected=null;render();return}const top=to.at(-1);const legal=type==='foundation'?cards.length===1&&card.suit===pile&&card.rank===(top?top.rank+1:1):(!top?card.rank===13:top.up&&red(top)!==red(card)&&card.rank===top.rank-1);if(!legal){message('Déplacement impossible : alterne les couleurs en descendant ; seuls les rois vont dans une colonne vide.');window.retroSound?.('error');return}remember();from.splice(selected.index);to.push(...cards);if(from.length&&selected.type==='column')from.at(-1).up=true;selected=null;moves++;window.retroSound?.('card');render();if(foundations.every(p=>p.length===13)){message('Bravo ! Les 52 cartes sont rangées en '+moves+' coups.');window.retroSound?.('win')}else message('Carte déplacée · '+moves+' coups')}
function choose(type,pile,index){if(selected){move(type,pile);return}const list=type==='column'?columns[pile]:type==='waste'?waste:foundations[pile];if(!list[index]?.up)return;if(type==='column'){const tail=list.slice(index);if(tail.some((c,i)=>i&&(!c.up||red(c)===red(tail[i-1])||c.rank!==tail[i-1].rank-1)))return}selected={type,pile,index};render();message('Sélectionne une colonne ou la fondation de la même enseigne. Échap annule.')}
function cardButton(c,type,pile,index){const b=document.createElement('button');b.className='sol-card'+(c.up?'':' back')+(red(c)&&c.up?' red':'');if(selected?.type===type&&selected.pile===pile&&index>=selected.index)b.classList.add('chosen');b.setAttribute('aria-label',c.up?rank(c)+' '+suits[c.suit]:'Carte face cachée');if(c.up)b.innerHTML='<span>'+rank(c)+'<br>'+suits[c.suit]+'</span><b>'+suits[c.suit]+'</b>';b.onclick=()=>choose(type,pile,index);b.disabled=!c.up;return b}
function render(){content.innerHTML='<div class="solitaire"><div class="sol-toolbar"><button class="sol-new">Nouvelle partie</button><button class="sol-undo" '+(!history.length?'disabled':'')+'>Annuler</button><span>'+moves+' coups</span></div><div class="sol-table"><div class="sol-top"></div><div class="sol-columns"></div></div><p class="sol-help">Pioche une carte à la fois. Sélectionne une carte puis sa destination.<br>Colonnes : couleurs alternées, du roi à l’as. Fondations : de l’as au roi.</p></div>';const top=content.querySelector('.sol-top'),draw=document.createElement('button');draw.className='sol-card '+(stock.length?'back':'empty');draw.textContent=stock.length?'':waste.length?'↻':'—';draw.setAttribute('aria-label',stock.length?'Piocher une carte':'Recycler la défausse');draw.onclick=()=>{if(!stock.length&&!waste.length)return;remember();if(stock.length)waste.push({...stock.pop(),up:true});else{stock=waste.reverse().map(c=>({...c,up:false}));waste=[]}selected=null;moves++;window.retroSound?.('card');render()};top.append(draw);if(waste.length)top.append(cardButton(waste.at(-1),'waste',0,waste.length-1));else{const empty=document.createElement('div');empty.className='sol-card empty';top.append(empty)}const spacer=document.createElement('div');top.append(spacer);foundations.forEach((pile,i)=>{const b=pile.length?cardButton(pile.at(-1),'foundation',i,pile.length-1):document.createElement('button');if(!pile.length){b.className='sol-card empty';b.textContent=suits[i];b.setAttribute('aria-label','Fondation '+suits[i]);b.onclick=()=>move('foundation',i)}top.append(b)});const grid=content.querySelector('.sol-columns');columns.forEach((pile,i)=>{const col=document.createElement('div');col.className='sol-column';col.style.minHeight=(100+Math.max(0,pile.length-1)*26)+'px';const empty=document.createElement('button');empty.className='sol-card empty';empty.textContent='K';empty.setAttribute('aria-label','Colonne '+(i+1));empty.onclick=()=>move('column',i);col.append(empty);pile.forEach((c,j)=>{const b=cardButton(c,'column',i,j);b.style.top=j*26+'px';col.append(b)});grid.append(col)});content.querySelector('.sol-new').onclick=reset;content.querySelector('.sol-undo').onclick=()=>{if(!history.length)return;const old=JSON.parse(history.pop());({stock,waste,foundations,columns,moves}=old);selected=null;render();message('Dernier mouvement annulé.')};content.onkeydown=e=>{if(e.key==='Escape'){selected=null;render()}}}
reset();
}
